@startuml Diagrama de Casos de Uso
'https://plantuml.com/use-case-diagram

left to right direction

rectangle {

    (Cadastrar escola) as (UC01)
    (Cadastrar Insumo) as (UC02)
    (Cadastrar Fornecedor) as (UC03)
    (Cadastrar Usuario) as (UC04)
    (Consultar Histórico de movimentações) as (UC05)
    (Movimentar Itens) as (UC06)
    (Emitir Guia de Movimentação) as (UC07)
    (Consultar Estoque de Escola) as (UC08)
}

Administrador -> (UC01)
Administrador --> (UC02)
Administrador --> (UC03)
Administrador ---> (UC04)
Administrador ---> (UC05)
Administrador ---> (UC06)
Administrador --> (UC08)

(UC05) <--- Usuario 
(UC06) <--- Usuario
(UC08) <--- Usuario

(UC05) <. (UC07) : <<extend>>

@enduml